(in-package :cs325-user)

(defun show-list (lst)
  (cond ((atom lst) (format t "~A" lst))
        (t (format t "[")
           (do ((l lst (cdr l)))
               ((atom l)
                (unless (null l)
                  (format t ". ~A" l)))
               (show-list (car l))
               (when (cdr l)
                 (format t " ")))
           (format t "]"))))

; (defun show-dots (lst)
;   (cond ((atom lst) lst)
;         (t (format nil "(~A . ~A)" 
;                    (show-dots (car lst))
;                    (show-dots (cdr lst))))))

(defun show-dots (lst)
  (cond ((atom lst) lst)
        (t (do ((l lst (cdr l)))
               ((null l) nil)
               (princ (show-dots (car l)))
               (princ (show-dots (cdr l)))))))