(in-package :cs325-user)

(defun show-dots (lst)
  (format t "~A" (generate-dotted-string lst)))

(defun show-list (lst)
  (cond ((null lst) (princ lst))
        ((atom lst) (princ lst))
        (t (princ "[")
           (do ((l lst (cdr l)))
               ((null l) (princ "]"))
               (cond ((atom l)
                      (princ (format nil ". ~A]" l))
                      (return-from show-list))
                     (t (show-list (car l))
                        (when (cdr l)
                          (princ " ")))))))
  nil)

(defun generate-dotted-string (lst)
  (cond ((null lst) nil)
        ((atom lst) lst)
        (t (format nil "(~A . ~A)" 
                   (generate-dotted-string (car lst))
                   (generate-dotted-string (cdr lst))))))