(in-package :cs325-user)

(defun show-dots (lst)
  (format t "~A" (generate-dotted-string lst)))

(defun show-list (lst)
  (cond ((null lst) (print lst))
        ((atom lst) (print lst))
        (t (princ "[")
           (do ((l lst (cdr l)))
               ((null l) (princ "]"))
               (cond ((atom (car l))
                      (princ ".")
                      (cond ((null (cadr l)) (princ (format nil "~A" (car l))))
                            (t (princ (format nil "~A " (car l))))))
                     (t
                       (cond ((null (cadr l)) (show-list (car l))) 
                             (t (show-list (car l)) (princ " "))))))))
  nil)

(defun show-list (lst)
  (cond
    ((or (null lst) (atom lst)) (princ lst))
    (t (prin1 #\[)
                 (do ((l lst (rest l)))
                     ((null l) (prin1 #\]))
                     (cond ((atom l)
                            (prin1 #\.)
                            (prin1 #\space)
                            (prin1 l)
                            (prin1 #\])
                            (return-from show-list))
                           (t (show-list (car l))
                              (when (cdr l)
                                (prin1 #\space)))))))
  nil)

(defun generate-dotted-string (lst)
  (cond ((null lst) nil)
        ((atom lst) lst)
        (t (format nil "(~A . ~A)" 
                   (generate-dotted-string (car lst))
                   (generate-dotted-string (cdr lst))))))